# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69b0684646a7c1dbd883bdd9a44790cc0e43703954d8d3ca674f5cc9bb7766fe17a2483e32bc2a0098044a24ca0f96688a892266369c4b08216ef5162b21c383

test:
  secret_key_base: 937da8caacf62d30b6824ca5acab2e490827a67a745a0cb5f6151906db8c41b0fad9a09e65afecee0b497ab61826ca05e1f2d5cb399f1a27a1bdb4a90d3f5860

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
